### ISSUE TITLE
Multiple Destinations

### ISSUE THREAD

**Issue by kousu** [GetPublii/Publii#490] opened 2019-06-22 16:27 UTC
Following up from https://publii.ticksy.com/ticket/1992756/, it would be helpful if Publii understood multiple upload targets, to enable backup sites, and to allow separate staging/production sites.

I think this is only a 'nice to have' feature, since you could use Publii with "manual" output and then script uploads using the manual mode.

**Comment by dziudek** [comment] 2022-09-03 10:17
Duplicate of https://github.com/GetPublii/Publii/issues/296

**Closed by dziudek** 2022-09-03 10:17 UTC
