### ISSUE TITLE
[Bug]: Upload control in Repeater Field (settingDisplay: tabs) 

### ISSUE THREAD

**Issue by gpsblues** [GetPublii/Publii#1816] opened 2024-11-19 07:53 UTC
### Operating system

Win 11

### Publii version

0.46.2 (build 16966)

### Post editor

None

### Bug description

When using the `Repeater` field with the `upload` control in a `plugin.json` file, and `"settingsDisplay": "tabs"`, the uploaded image is incorrectly saved in the folder:  
`"\Publii\sites\mysite\input\media\plugins"`  
instead of the correct folder:  
`"\Publii\sites\mysite\input\media\plugins\myplugin"`.  

Additionally, the preview of the uploaded image in the control remains empty.  

If `"settingsDisplay": "fieldsets"` is used instead (with no other changes to the code), the issue does not occur, and everything works as expected.

### Steps to reproduce

Configure a ` plugin.json` file with the following minimal setup:

```json
{
    "name": "A Slider",
    "description": "",
    "license": "GPL-3.0",
    "author": "gpsblues",
    "version": "1.0.0",
    "scope": "site",
    "minimumPubliiVersion": "0.40.0",
    "usePluginSettingsView": false,
    "useCustomCssForOptions": false,
    "settingsDisplay": "tabs",
    "config": [
        {
            "name": "imageUploader",
            "label": "",
            "group": "Upload images",
            "type": "repeater",
            "value": [],
            "hasEmptyState": false,
            "hideLabels": false,
            "translations": {
                "addItem": "Add",
                "duplicateItem": "Duplicate",
                "emptyState": "Click the button below to add a new image.",
                "removeItem": "Delete"
            },
            "note": "",
            "structure": [
                {
                    "name": "image",
                    "label": "Image",
                    "type": "upload",
                    "value": "",
                    "width": 100
                }
            ]
        }
    ]
}
```

**Comment by dziudek** [comment] 2024-12-21 12:14
@gpsblues - thanks for finding this issue - it was caused by lack of one param in the mentioned configuration. Will be fixed in v.0.46.3

**Closed by dziudek** 2024-12-21 12:14 UTC
