### ISSUE TITLE
Whitespaces aren't handled correctly in html blocks

### ISSUE THREAD

**Issue by ciriousjoker** [GetPublii/Publii#800] opened 2020-08-27 05:04 UTC
It seems like a whitespace before a tag will get removed.

**Example**
`test <div>` -> `test<div>`

**Forcing whitespace with \&nbsp; results in this:**
`test &nbsp;<div>` -> `test &<div>`
`test&nbsp;<div>` -> `test&<div>`

This issue can be circumvented (at least somewhat), by using the WYSWYG editor, but that one alters the html (by adding line breaks for no reasonI). The other option (the one I went with) is directly editing the db.sqlite file with the correct html content, but that's far from the optimal solution.

**Comment by dziudek** [comment] 2022-09-06 10:05
It seems that this issue is caused by HTML compression enabled or via TinyMCE configuration. Any text fragments which requires preserving whitespaces should be wrapped into `<pre>` tags in TinyMCE. Alternatively for preserving whitespaces block editor can be used.

I am closing this issue now. If any new details will appear - feel free to reopen it.

**Closed by dziudek** 2022-09-06 10:05 UTC
Labels: bug
