### ISSUE TITLE
Random, unintentional duplication of menu items

### ISSUE THREAD

**Issue by bobmitro** [GetPublii/Publii#820] opened 2020-09-14 08:27 UTC
Often when adding a new tag to the main menu, it automatically creates a duplicate menu item with the same item and is appended to the end of the menu. After moving the item up into a submenu, we still get a duplicate. Deleting one of the duplicates removes both (all) of them. 

Oddly, sometimes while dragging the item around in the menu as a submenu item, it will duplicate again creating the 3rd copy.

![screen](https://user-images.githubusercontent.com/1391007/93062156-d6e20f80-f674-11ea-967b-cd2feec08aa3.jpg)

**Comment by dziudek** [comment] 2022-09-06 10:08
I cannot reproduce this issue right now - it could be fixed in the meantime. Reopen it if it is still possible to reproduct this issue.

**Closed by dziudek** 2022-09-06 10:08 UTC
Labels: bug
