### ISSUE TITLE
Servers - GitHub Pages not working

### ISSUE THREAD

**Issue by invisart-master** [GetPublii/Publii#545] opened 2019-08-17 15:58 UTC
Hello Publii team,

I've created the GitHub repository and went through all steps in the documentation, and "Test connection" works give me "Success! ..." message, but when I press "Save Settings" button nothing happens, data not saved. What to do? 

It's MacOS, version of Publii - Version 0.35.1 (0.35.1)

**Comment by dziudek** [comment] 2019-08-17 20:02
Hi,

In fact if the connection test is success the Github settings should be automatically saved. It does not work for you?

**Comment by invisart-master** [comment] 2019-08-19 08:48
Hi @dziudek,

Yes, does not work, settings is not saved, the button "View Website" is grey and disabled.

**Comment by dziudek** [comment] 2019-08-19 09:39
Hi @invisart-master ,

Could you check if you are able to save settings without click on "Test connection"?

**Comment by dziudek** [comment] 2019-08-19 09:43
I was able to reproduce this kind of issue, but only once while creating a new website and while I was adding directly the server settings to this website. But later I was unable to reproduce this issue in the same way. Looks like some random memory leak or unclosed test connection process.

**Comment by invisart-master** [comment] 2019-08-20 09:36
I've tried 5 times at least, with and without test connection, with company repo and personal, nothing in console. It just not work.

**Comment by dziudek** [comment] 2019-08-21 17:18
Are you testing this issue on the same website? Could you try to check it on the other (new) website in Publii? Other deployment methods are working in your case?

**Comment by invisart-master** [comment] 2019-08-22 06:57
Since I'm quite busy on my 5/8, I will try GitLab later this week and let you know. One thing I can tell is that I installed this version of Publii on top of previous.

**Comment by dziudek** [comment] 2019-08-22 20:02
Please also check one think if the issue occurs again - open the Keychain Access application and on the left sidebar please click on "login" to show context menu and then please select "Lock keychain 'login'". Then please click again and please select from the context menu "Unlock keychain 'login'" - maybe it will help as I have discovered that after some macOS updates this issue with keychain occurs randomly and prevents some apps from working correctly.

I will add an additional checks on such places to display a proper information about the issue if it is an reason.

**Comment by invisart-master** [comment] 2019-08-27 09:07
I'm sorry, I had a lot of work during the weekend, and could not try another deployment method.

**Comment by invisart-master** [comment] 2019-09-02 17:06
@dziudek your suggestion with "Lock/Unlock keychain 'login'" works, thank you very much!

**Comment by dziudek** [comment] 2019-09-03 08:52
@invisart-master - I reopened this isssue as I will close it when we will implement a notification about keychain access problems in Publii

**Comment by catweazle-git** [comment] 2019-09-06 17:33
I've the same problem on a fresh installed archlinux and the newest version 0.35.1. I'm not able to save the server settings even though the ftp connection test is success (after several failed attempts). Switching the protocol to "manual upload" shows the same behavior: can't save ... But under Windows 10 there's no problem to save the server settings (on the same PC).

**Comment by Moltkex** [comment] 2020-12-07 00:34
Hi, 
I'm having this same issue. My system's Debian Buster. After configuring everything Publii won't save settings, thus unable to sync. Also, I just started using Publii and not sure but I don't get a "protocol" option to choose from, all I can see is "api server" and reads   "**api.github.com**", however, instructions https://getpublii.com/docs/host-static-website-github-pages.html#syncingyourpubliistaticsitewithgithub "**Protocol - Select GitHub Pages from the drop-down list.**" so either something's wrong with Publii (I'm using the appimage, by the way) or the docs need to be updated to reflect that.

**Comment by Lesik** [comment] 2021-02-03 23:36
I am facing the same problem, also on Debian Buster (likely just a coincidence though). I tried SFTP and GitLab, and the connection test is successful. The save button does nothing, and the "Configure server" button doesn't change to "Sync your website". I'm also using the AppImage.

**Comment by invisart-master** [comment] 2021-02-06 10:24
Works fine, all uploaded from Deepin 20.1 - Debian 10.7, Linux 5.10

**Comment by Moltkex** [comment] 2021-02-06 23:25
> Works fine, all uploaded from Deepin 20.1 - Debian 10.7, Linux 5.10

This version, 0.37.3 (build 13870) Beta? I'm using the appimage https://cdn.getpublii.com/Publii-0.37.3.AppImage

**Comment by Verassitnh** [comment] 2021-02-10 19:01
@catweazle-git @Moltkex @Lesik Installing `gnome-keyring` fixed it for me.

**Comment by Moltkex** [comment] 2021-02-10 22:06
> @catweazle-git @Moltkex @Lesik Installing `gnome-keyring` fixed it for me.

Are you using the appimage or the .deb file?

**Comment by Verassitnh** [comment] 2021-02-10 23:50
@Moltkex Its because Publii needs to store the GitHub API key on your computer. It was impossible to do that because you did not have a keyring manager installed.

> Are you using the appimage or the .deb file? I use KDE by the way.

Since I use Archlinux, I am using the aur package.

**Comment by Moltkex** [comment] 2021-02-11 00:27
> @Moltkex Its because Publii needs to store the GitHub API key on your computer. It was impossible to do that because you did not have a keyring manager installed.
> 
> > Are you using the appimage or the .deb file? I use KDE by the way.
> 
> Since I use Archlinux, I am using the aur package.

Since I use KDE, does that mean all I needed to do was probably enable the KDE wallet? Since I don't use it, thus it's disabled. It never occurred to me to try that, I'll try and see what happens. There should be something in the docs stating that,  "If you have problems to configure the server, make sure there's a **keyring manager** available on your system"   or something like that.

**Comment by dziudek** [comment] 2021-02-20 18:29
@Moltkex - the next release of Publii will display a proper message in such case: https://github.com/GetPublii/Publii/issues/739

**Closed** 2021-02-20 18:30 UTC
Labels: bug

**Comment by petrovsky17** [comment] 2023-02-14 09:44
Same issue happens for me. I downloaded newest app version, installed it on my mac with M2, filled all the fields for gihub pages, testing connection says "success", but cannot save it and "visit website" button is gray and unclickable. Tried solution with keychain access but the option to lock keyichain is also gray and cannot lock or unlock it. Do you have any other solutions for macs with intel chip please?

**Comment by petrovsky17** [comment] 2023-02-14 10:01
So I had the same issue. Downloaded newest app version, installed it on my mac with M2, filled all the fields for gihub pages, testing connection said "success", but coudn't save it and "visit website" button was gray and unclickable. Tried solution with keychain access but the option to lock keyichain was gray and coudn't lock or unlock it. Fiddled around with it and in Login  keychain found "publii-gh-token". Opened it and saw that the field "password" at the bottom was empty, so pasted there a github acess token, saved and it resolved the issue. Hope this works for others as well :)
