### ISSUE TITLE
S3: Cannot set empty relative URL

### ISSUE THREAD

**Issue by jchown** [GetPublii/Publii#754] opened 2020-06-17 15:02 UTC
We want to host using relative URLs without a prefix, but on the S3 settings you cannot set this.

If you tick "Use relative URLs" and clear the URL text box it silently uses "./" instead.

**Comment by jchown** [comment] 2020-06-17 15:40
If you set it to the empty string directly in site.config.json then sync fails with a "make sure your domainn name is set" message.

**Comment by dziudek** [comment] 2020-07-09 17:19
I am closing as duplicate of this issue: https://github.com/GetPublii/Publii/issues/709

**Closed by dziudek** 2020-07-09 17:19 UTC
