### ISSUE TITLE
Github-Repository-Setting "Custom domain" gets lost when syncing using gh-pages

### ISSUE THREAD

**Issue by vchrizz** [GetPublii/Publii#286] opened 2019-01-28 20:55 UTC
When clicking the button "Sync your website" using Server Settings Protocol "Github Pages", on Github in the Repository Settings under "GitHub Pages" the setting "Custom domain" is cleared out after successful upload.
After setting "Custom domain" everything works as expected.
Syncing the website again, clears "Custom domain" again, so we have to set it every time when syncing.
Same behaviour with recent version of Windows client (v.0.32.4 (build 11275) Beta) and MacOS client (v.0.32.4 (build 11273) Beta).

**Comment by dziudek** [comment] 2019-01-31 15:55
Hi,

Did you set your custom domain in the Publii settings?

The CNAME file is visible in your repository after the deployment?

**Comment by dziudek** [comment] 2019-02-25 18:07
I am closing this issue as I did not received any more details which can help to investigate this issue.

**Comment by joegasper** [comment] 2019-10-20 03:10
I will pick this up to help others as I encountered this "problem" with custom GitHub Pages.

Set the GitHub repository custom domain to your domain you are using.
On the Server Settings page for GitHub Pages, if you set the Domain field to "myusername.github.io/myrespository" (as per instructions) then the CNAME file is removed after a sync - it is not visible in the repository and the site goes GitHub-level 404. 

Adding the custom domain setting to the repository will recreate the CNAME file and the site will work again.

If I set the Domain field for the Destination Server on the Server Settings page to my custom domain name (the same value I put in the repository's custom domain name field), then the CNAME file is created/remains correctly, and the site works correctly.

Perhaps the instructions could be a bit clearer?

**Comment by dziudek** [comment] 2019-10-21 17:12
Hi @joegasper ,

As far as I know the CNAME file is not necessary if you are using github.io domains. Maybe the 404 error is caused by not refreshed DNS servers. But the app behaviour is correct - the CNAME file is required only if you are using custom domain.

**Comment by joegasper** [comment] 2019-10-24 05:17
Correct, the CNAME file is only needed/created when using a custom domain name. The 404 was resulting because Publii was removing the CNAME file on sync - because I was initially not properly completing the Domain field for the Destination Server on the GitHub server setting page in Publii.

I believe it would help if you added a note, something like below, to the https://getpublii.com/docs/host-static-website-github-pages.html in the bullet item:

Domain - This will be your Github repository path, which uses the format "YOUR_USERNAME.github.io/ YOUR_REPOSITORY_NAME".
**If using a custom domain name, set this field to just the custom domain name:
"www.mycustomdomain.tld".**

**Comment by dziudek** [comment] 2019-11-12 07:24
Reopened to add a note from: https://github.com/GetPublii/Publii/issues/286#issuecomment-545748311

**Comment by sijanec** [comment] 2020-02-13 17:44
There is indeed a bug in the latest Publii build for Windows regarding the CNAME file. As observed, the CNAME file is overwritten with "//domain.example" when relative protocol is set in the server settings. This would of course not work as the CNAME fromat accepts only FQDNs without any prefixed slashes.

**Comment by dziudek** [comment] 2020-03-15 10:59
@sijanec - I have improved the the CNAME file generating - now in the next prerelease planned for the next week it shouldn't contain any slashes at the beginning.

**Closed** 2020-03-15 10:59 UTC
Labels: bug, improvement

**Comment by sijanec** [comment] 2020-03-15 12:33
thank you very much for the fix

**Comment by khera-shanu** [comment] 2024-08-18 15:51
I was facing this same today with latest version, this is how I fixed it:

Add CNAME file here (for Mac): `/Users/<user name>/Documents/Publii/sites/<site name>/input/root-files`
