### ISSUE TITLE
Unable to render on Linux

### ISSUE THREAD

**Issue by novalore** [GetPublii/Publii#165] opened 2018-10-14 08:16 UTC
I have a website that was built with Publii on Windows and now I'm trying to modify it in linux (kubuntu 16.10 - Publii 0.30.4).
When trying to render it I get the following error:
**Rendering process crashed
Checkout the rendering-errors.log and rendering-process.log files under Tools -> Log viewer.**

Then going to check log files here is what I get:
**rendering-errors.log**
This log file is empty...

**rendering-process.log**
CONFIG: 94.350ms
TAGS POST COUNT - QUERY: 348.913ms
TAGS POST COUNT - STORE: 0.119ms
TAGS - QUERY: 2.351ms
TAGS - STORE: 0.018ms
AUTHORS POST COUNT - QUERY: 63.029ms
AUTHORS POST COUNT - STORE: 0.051ms
AUTHORS - QUERY: 2.737ms
AUTHORS - STORE: 5.271ms
FEATURED IMAGES - QUERY: 180.303ms
[WARNING] renderer-context.js: wrong image path - missing dimensions for: /home/faust/Documents/Publii/sites/coopstarter-guidebook/input/media/posts/15
[WARNING] renderer-context.js: wrong image path - missing dimensions for: /home/faust/Documents/Publii/sites/coopstarter-guidebook/input/media/posts/14
[WARNING] renderer-context.js: wrong image path - missing dimensions for: /home/faust/Documents/Publii/sites/coopstarter-guidebook/input/media/posts/11
[WARNING] renderer-context.js: wrong image path - missing dimensions for: /home/faust/Documents/Publii/sites/coopstarter-guidebook/input/media/posts/13
[WARNING] renderer-context.js: wrong image path - missing dimensions for: /home/faust/Documents/Publii/sites/coopstarter-guidebook/input/media/posts/12
FEATURED IMAGES - STORE: 2.322ms
POST TAGS - QUERY: 3.930ms
POST TAGS - STORE: 0.053ms
POSTS - QUERY: 54.166ms
POSTS - STORE: 67.450ms
CONTENT DATA: 737.270ms
HOME: 711.683ms
POSTS: 855.227ms
TAGS: 3.665ms
AUTHORS: 147.769ms
404: 29.690ms
SEARCH: 27.436ms
FEEDS: 413.263ms
CSS: 591.673ms

**Comment by GetPublii** [comment] 2018-10-14 08:28
Hey novalore,
Could you provide us with your website backup?

**Comment by novalore** [comment] 2018-10-14 08:40
Yes, sure. 

> Hey novalore,
> Could you provide us with your website backup?

Yes, sure.
https://drive.google.com/open?id=1fcauNCXtGoLwcjLTdVEVA4mwOKm7vU8Q

It is also published on https://coopstarter.github.io/IO4guidebook/ in its current unfinished version

**Comment by Areahints** [comment] 2018-10-16 10:43
hi @novalore could you walk me through the steps you used to get publii configured correctly on ubuntu. did you use the .deb or appimage file, because i have to use gksudo on publii and currently cant preview or  add Github pages as server destination because when i click that button it doesn't show me a dialog that it has saved the info i added, the twist is that i can test the connection and it says its all good!

**Comment by Areahints** [comment] 2018-10-16 10:44
i honestly suspect its a permission issue but i dont know where to start troubleshooting exactly :disappointed:

**Comment by novalore** [comment] 2018-10-16 19:28
I installed Publii using the .deb package.
You to know, though, that the website was started on Publii on Windows and then the directory was uploaded to Google drive and downloaded on Linux to modify it

**Comment by dziudek** [comment] 2018-10-18 17:48
Hi @novalore,

After deeper debugging I have found that your issue was caused by non-existing media/posts directory. It will be fixed with the next release.

**Closed** 2018-10-18 17:48 UTC

**Comment by typeetfunc** [comment] 2018-12-06 21:03
@dziudek @GetPublii  I has similar error.
Mac OS. v.0.31.3 (build 11117) Beta
When trying to render it I get the following error:
Rendering process crashed
Checkout the rendering-errors.log and rendering-process.log files under Tools -> Log viewer.

Then going to check log files here is what I get:
rendering-errors.log
This log file is empty...

rendering-process.log

CONFIG: 67.563ms
TAGS POST COUNT - QUERY: 507.961ms
TAGS POST COUNT - STORE: 0.151ms
TAGS - QUERY: 25.621ms
TAGS - STORE: 26.618ms
AUTHORS POST COUNT - QUERY: 130.624ms
AUTHORS POST COUNT - STORE: 0.034ms
AUTHORS - QUERY: 1.426ms
AUTHORS - STORE: 0.715ms
FEATURED IMAGES - QUERY: 119.807ms
FEATURED IMAGES - STORE: 83.083ms
POST TAGS - QUERY: 73.698ms
POST TAGS - STORE: 0.421ms
POSTS - QUERY: 1889.433ms
POSTS - STORE: 1921.926ms
CONTENT DATA: 4784.020ms
HOME: 150745.733ms
A HTML parsing error occurred during the compression - uncompressed HTML returned. Error details: {}
A HTML parsing error occurred during the compression - uncompressed HTML returned. Error details: {}

My backup: https://www.dropbox.com/s/vxsslq8lfn5s4zc/backup-12-06-2018-23-58-57.tar?dl=0
