### ISSUE TITLE
Language support issues

### ISSUE THREAD

**Issue by xudadi** [GetPublii/Publii#669] opened 2020-02-10 11:39 UTC
Can I support multi-language settings, I think English and Chinese are necessary, and many people use English and Chinese，Thank you

**Comment by mbnoimi** [comment] 2020-02-20 07:19
In addition to this request I suggest to add RTL/LTR layout direction too.

**Comment by bobmitro** [comment] 2020-02-22 11:58
Duplicate of  #628

**Closed by bobmitro** 2020-02-22 11:58 UTC
