### ISSUE TITLE
cdn.getpublii.com inaccessible

### ISSUE THREAD

**Issue by jkpe** [GetPublii/Publii#580] opened 2019-10-04 10:31 UTC
Hi folks,

When attempting to download Publii or a theme from the marketplace I get an error in my browser.

Affected: https://cdn.getpublii.com/themes/simple_2.0.3.0.zip

Safari doesn't give me much info, Firefox says:

"cdn.getpublii.com has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site."

"Firefox does not trust this site because it uses a certificate that is not valid for cdn.getpublii.com. The certificate is only valid for cdn.pushrcdn.com."

**Comment by paulocoghi** [comment] 2019-10-04 11:55
Apparently it's working now.

**Comment by paulocoghi** [comment] 2019-10-04 11:55
Could you test again?

**Comment by jkpe** [comment] 2019-10-04 12:57
I still see the same issue

**Comment by internettips** [comment] 2019-10-04 13:03
Likewise here: same problem with download. Of course, the "Alternative download" link source works okay.

**Comment by paulocoghi** [comment] 2019-10-04 14:26
I am using Cloudflare DNS (1.1.1.1, 1.0.0.1) and Firefox 69, and I am not getting this error.

**Comment by paulocoghi** [comment] 2019-10-04 14:28
Hmmm, I believe that I understand now what is happening. The different servers on the PushrCDN are not performing equal.

Some of them already updated the Let's Encrypt certificate, but other don't. This explains why some of you are getting this error (the servers near you are not serving the right certificate), and some people, like me, are not.

**Comment by paulocoghi** [comment] 2019-10-04 14:30
@dziudek , I suggest you to open a ticket on PushrCDN to explain this issue to them.

**Comment by paulocoghi** [comment] 2019-10-23 17:37
@bobmitro , as @mxmilkb said, this issue is still happening.

**Comment by dziudek** [comment] 2019-11-12 08:58
The issue should be fixed after latest migration done over the last weekend. If anyone will be still affected - please report. At this moment - the issue is closed.

**Closed by dziudek** 2019-11-12 08:58 UTC
