### ISSUE TITLE
removed content when embedding form

### ISSUE THREAD

**Issue by kevinlai80** [GetPublii/Publii#630] opened 2019-12-06 18:11 UTC
Hi

I'm trying to do an advanced embed of Google Form on my publii website. I want to avoid the simple iframe.
The code works on a simple html page, as you can test here : [https://jsfiddle.net/aw9zLhsc/](https://jsfiddle.net/aw9zLhsc/)

When I post the code on a post, it works partially.
The content is sent to my Google Form, but the custom thanks page does not work.

Here is the code :

```
<script type="text/javascript">var submitted=false;</script>

<iframe name="hidden_iframe" id="hidden_iframe" style="display:none;" onload="if(submitted) {window.location='https://getpublii.com';}"></iframe>

<form action="https://docs.google.com/forms/u/0/d/e/1FAIpQLScRHQ0TrxL7N1kJQy6qL-KPNslva7_2NZtK0k8hkStFFY-c4w/formResponse" method="post" target="hidden_iframe" onsubmit="submitted=true;">

<label>name</label>
<input name="entry.1734262663" type="text" required/>
<br>

<label>surname</label>
<input name="entry.387555578" type="text" required/>
<br>

<input type="submit" value="Send" />

</form>
```

BUT, when entered by html source code on a post and the change applied,

this code : `<script type="text/javascript">var submitted=false;</script>`
become : `<script type="text/javascript">// <![CDATA[ var submitted=false; // ]]></script>`
why ? but it still seems to work so

and in "form action" I loose : `onsubmit="submitted=true;"`
which is the most problematic

Thanks

**Comment by dziudek** [comment] 2019-12-09 17:35
Hi, 

Please read this topic: https://getpublii.com/forum/topic/html-code-editors-removes-code/

I am closing this issue as it is not a bug, more complex code needs TinyMCE configuration adjustments.

**Closed by dziudek** 2019-12-09 17:35 UTC
