### ISSUE TITLE
CDN links resolve to 502 bad gateway

### ISSUE THREAD

**Issue by DarkLog1x** [GetPublii/Publii#519] opened 2019-07-22 07:56 UTC
Hi, thanks for making such a great tool. 

It seems like the cdn links at https://getpublii.com/download/ lead to a 502 bad gateway error for me. I have tried to download all of the different files (Mac, Windows, and Linux) and they all fail for me with the same error.
I however am able to use the alternative download links without a problem.
This is similar to  issue #387 but wanted to give a little bit more information on the problem.

**Comment by dziudek** [comment] 2019-07-22 08:24
Hi,

From which location are you downloading Publii? Are you using some proxy or VPN? Sometimes the CDN shows 502 error for some locations, that's why we have created the alternative download :)

**Comment by DarkLog1x** [comment] 2019-07-22 14:13
Hi, I am downloading Publii from The Netherlands. I have tried the cdn links with both vpn and normal home connection with both of them returning 502 errors. It is very strange that I am getting the errors but the alternative links do work. Just wanted to point this out in-case this was a larger problem.

**Comment by tlandmangh** [comment] 2019-07-23 07:27
I have the same issue when I try to download Publii just like DarkLog1x. I'm also from the Netherlands. In addition I can report that the same gateway error occurs when I try to download from the marketplace. I assume because those links use the same CDN for the downloads.

**Comment by pixelastic** [comment] 2019-07-30 08:25
Just wanted to chime in saying that I cannot download publii from the CDN links either (https://cdn.getpublii.com/Publii-0.35.0.deb) 

![image](https://user-images.githubusercontent.com/283419/62113104-4865cf80-b2b4-11e9-989c-b9e580309809.png)

I'm trying to access it from France, with no specific proxy nor VPN. Alternative download works fine.

**Comment by dziudek** [comment] 2019-09-03 20:00
Sorry, but I forgot about this issue. We have got a message some time ago that the access to CDN should be fixed. Can anybody who had this issue confirm that now CDN is working?

**Comment by tlandmangh** [comment] 2019-09-05 06:41
I can confirm that the CDN now works. Both with FireFox and Chrome on 
Windows 7.

Op 3-9-2019 om 22:00 schreef Tomasz Dziuda:

**Comment by pixelastic** [comment] 2019-09-10 11:30
I can confirm that it's now fixed and works from France.

**Closed** 2019-09-10 12:09 UTC

**Comment by nam1962** [comment] 2019-12-15 08:14
Hi, 
I got `Could not resolve host: cdn.getpublii.com` from Proximus Belgium, apparently a lying DNS as I had to log on a french VPN to resolve.
...could be interesting to grasp why Could not resolve cdn.getpublii.com is censored.
