### ISSUE TITLE
Push to Multiple Servers

### ISSUE THREAD

**Issue by slashtechno** [GetPublii/Publii#973] opened 2021-05-10 22:09 UTC
I was wondering if it is possible to sync a site with multiple servers. For example, can I have an FTP server and a Github Pages site syncing to Publii?

**Comment by dziudek** [comment] 2022-09-03 10:17
Duplicate of https://github.com/GetPublii/Publii/issues/296

**Closed by dziudek** 2022-09-03 10:17 UTC

**Comment by slashtechno** [comment] 2022-09-03 13:52
> Duplicate of #296

Oh, apologizes, didn't realize there was a prior issue.
