### ISSUE TITLE
Bug "Sync cancel"

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#389] opened 2019-03-21 18:05 UTC
I have clicked the "Sync your website", then "cancel" and an error has been shown.
Screenshot: https://i.imgur.com/8BvSU9j.png
Operating system: Manjaro linux
Version publii: v.0.33.4 (build 11590) Beta

**Comment by dziudek** [comment] 2019-03-26 21:24
Hi,

It seems that this fix is not enough: https://github.com/GetPublii/Publii/issues/356

I cannot reproduce this issue on macOS, so I suppose that it is linux-related or even distribution-related issue.

**Comment by wuniversales** [comment] 2019-03-27 17:39
The error when starting the program does not appear, the error appears when pressing the following.
"sync your website" -> "sync your website" -> "ok"
Then press
"sync your website" -> "Cancel"
This will show the error.

> Hi,
> 
> It seems that this fix is not enough: #356
> 
> I cannot reproduce this issue on macOS, so I suppose that it is linux-related or even distribution-related issue.

**Comment by internettips** [comment] 2019-03-27 22:16
@wuniversales 

Using the latest version of macOS, for a brief period, I was able to reproduce this problem, but using only "Sync your website" > "Cancel". 

However, by:

1. Closing Publii v.0.33.4 (build 11590)
2. Waiting about 30 seconds and 
3. Restarting Publii ...

... the problem was no longer present. And so far, still okay.

**Comment by dziudek** [comment] 2021-03-07 12:25
I have implemented a "more brutal" version of closing deployment process - maybe it will help i v.0.38 :)

**Closed by dziudek** 2021-03-07 12:25 UTC
Labels: bug
